#!/usr/bin/env bash

# 1. 获取 msg 文本
msg=`cat ${1}`
echo -e "\n\n『commit-msg 为 \"${msg}\"』\n "

# 2. 编写正则
headerReg="^(feat|fix|style):"

# 3. 进行正则匹配
if [[ $msg =~ $headerReg ]]
then
  exit 0
else
  echo -e '[该 msg 不符合规范，请在 msg 首部添加以下字段] \n '
  echo -e ' `feat: xxx`    →    A new feature'
  echo -e ' `fix: xxx`     →    A bug fix'
  echo -e ' `style: xxx`   →    Changes that do not affect the meaning of code'
  exit 1
fi


