#!/usr/bin/env node
const fs = require('fs');
const colors = require('colors');
const inquirer = require('inquirer');
const msgFile = process.argv[2];
const headerReg = /^(feat|fix|style):/;
const errOptions = [
  "1. 强制提交",
  "2. 重新输入 msg",
  "3. 给 msg 加上标识前缀",
  "4. 退出"
];
let msgChange = false; // 标记 msg 有没有被修改过

// 读取 msgFile
let getMsg = function() {
  return new Promise((resolve, reject) => {
    fs.readFile(msgFile, 'utf8', (err, data) => {
      if (err) reject(err);
      else resolve(data);
    })
  })
}

// 写入 msgFile
let writeMsg = function(msg) {
  return new Promise((resolve, reject) => {
    fs.writeFile(msgFile, msg, 'utf8', (err) => {
      if (err) reject(err);
      else resolve();
    })
  })
}

// 输入 msg 字符串
let inputMsg = function() {
  let inputPrompt = {
    type: 'input',
    message: '重新输入 msg: ',
    name: 'msg',
  };
  return inquirer.prompt(inputPrompt).then(answers => answers.msg);
}

// 校验 commit-msg
let testMsg = async function(msg) {
  let res = 0;
  console.log(colors.green(`Success: 你输入的 commit-msg  "${msg}"`));

  if (headerReg.test(msg)) {
    console.log(colors.green("Success: msg 校验通过 "));
    if (msgChange) await writeMsg(msg);
  } else {
    let errPrompt = {
      type: 'list',
      name: 'choose',
      choices: errOptions,
      message: colors.red("Error: msg 不符合规范，msg 必须以 ( feat | fix | style ) 开头，请选择以下操作以继续: ")
    };
    let index = await inquirer.prompt(errPrompt).then(answer => errOptions.indexOf(answer.choose));
    switch(index) {
      case 0:
        console.log("[强制提交]");
        res = 0;
        break;
      case 1:
        msgChange = true;
        res = await testMsg(await inputMsg());
        console.log("[重新输入]");
        break;
      case 2:
        console.log("[加上前缀]");
        res = 1;
        break;
      case 3:
        console.log("[退出]");
        res = 1;
        break;
      default:
        res = 1;
        console.log("异常");
        break;
    };
  }
  return res;
}


async function main() {
  let msg = await getMsg();
  let res = await testMsg(msg);
  console.log("最后的状态码是：", res);
  process.exit(res);
}

main();
 






