#!/usr/bin/env node
const fs = require('fs');
const colors = require('colors');
const inquirer = require('inquirer');

const msgFile = process.argv[2];
const headerReg = /^(feat|fix|style):/;
const errOptions = [
  "1. 强制提交",
  "2. 重新输入 msg",
  "3. 给 msg 加上标识前缀",
  "4. 退出"
];

// 获取 commit-msg → 返回一个 promise
let getMsg = function() {
  return new Promise((resolve, reject) => {
    fs.readFile(msgFile, 'utf8', (err, data) => {
      if (err) reject(err);
      else resolve(data);
    })
  })
}

// 输入 msg → 返回一个 promise
let inputMsg = function() {
  let inputPrompt = {
    type: 'input',
    message: '重新输入 msg: ',
    name: 'msg',
  };
  return inquirer.prompt(inputPrompt).then(answers => answers.msg);
}

// 校验 commit-msg
let testMsg = async function(msg) {
  console.log(colors.green(`Success: 你输入的 commit-msg  "${msg}"`));

  if (headerReg.test(msg)) {
    console.log(colors.green("Success: msg 校验通过 "));
    fs.writeFile(msgFile, msg, (err) => {
      if (err) {
        console.log(colors.red("Error: msg 修改失败"));
        process.exit(1);
      }
    });
    process.exit(0);
  } else {
    let errPrompt = {
      type: 'list',
      name: 'choose',
      choices: errOptions,
      message: colors.red("Error: msg 不符合规范，msg 必须以 ( feat | fix | style ) 开头，请选择以下操作以继续: ")
    };
    let index = await inquirer.prompt(errPrompt).then(answer => errOptions.indexOf(answer.choose));
    switch(index) {
      case 0:
        console.log("[强制提交]");
        process.exit(1);
        break;
      case 1:
        let msg = await inputMsg();
        res = await testMsg(msg);
        console.log("[重新输入]");
        break;
      case 2:
        res = 1;
        console.log("[加上前缀]");
        break;
      case 3:
        res = 1;
        console.log("[在 msg 前加前缀]");
        break;
      default:
        res = 1;
        console.log("退出");
        break;
    };

  }
  return res;
}
async function main() {
  let msg = await getMsg();
  let res = await testMsg(msg);
  console.log("最后的状态码是：", res);
  process.exit(res);
}

// main();
 
console.log(process.argv)







